#   Autor: Pedro Igor Martins dos Reis
#   Data: 26/12/2021
#   Arquivo: "alacritty.yml" - Configuração do terminal Alacritty

env:
  TERM: xterm-256color

window:
  padding:
    x: 10
    y: 10
  lines: 120
  columns: 120
  decorations: full
  dynamic_padding: true

  title: Alacritty
  dynamic_title: true

  class:
    instance: Alacritty
    general: Alacritty

scrolling:
  history: 500
  multiplier: 3

font:
  normal:
    family: Fira Code
    style: Regular
  bold:
    family: Fira Code
    style: Bold
  size: 14

  draw_bold_text_with_bright_colors: true

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

cursor:
  style:
      shape: Beam
      blinking: Always
      blink_interval: 750

      unfocused_hollow: true
      thickness: 0.15

live_config_reload: true

colors:
  primary:
    foreground: '#fdfdfd'
    background: '#282e3a'
  search:
    bar:
      foreground: '#fdfdfd'
      background: '#29303a'