font:
    normal:
        family: Fira Code
        style: Regular
    bold:
        family: Fira Code
        style: Bold
    size: 10

draw_bold_text_with_bright_colors: true

mouse:
    hints:
        launcher:
            program: xdg-open
            args: []
window:
    padding:
        x: 10
        y: 10
    decorations: full
    dynamic_title: false

dynamic_padding: true

colors:
    primary:
        background: '0x1d2021'
        foreground: '0xd4be98'
    normal:
      black:   '0x32302f'
      red:     '0xea6962'
      green:   '0xa9b665'
      yellow:  '0xd8a657'
      blue:    '0x7daea3'
      magenta: '0xd3869b'
      cyan:    '0x89b482'
      white:   '0xd4be98'
    bright:
      black:   '0x32302f'
      red:     '0xea6962'
      green:   '0xa9b665'
      yellow:  '0xd8a657'
      blue:    '0x7daea3'
      magenta: '0xd3869b'
      cyan:    '0x89b482'
      white:   '0xd4be98'
    search:
        bar:
            background: '#222222'
            foreground: '#c94d22'

background_opacity: 0.85

selection:
    semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
    save_to_clipboard: true

cursor:
    style:
        shape: Beam
        blinking: on